collectd:
  build: .
  privileged: true
  command: collectd -C /etc/collectd/collectd.conf -f
  volumes:
    - /proc:/host/proc
    - /opt/collectd:/etc/collectd
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
